version: "3.4"
services:
  busy:
    env_file:
      - .env
    build:
      context: .
      dockerfile: busyDockerfile
    image: '${REGISTRY_NAME}sushant21/${busybox}:latest'
  alp:
    env_file:
      - .env
    image: '${REGISTRY_NAME}sushant21/alpine:latest'
